### ISSUE TITLE
Exception in thread Thread-9 

### ISSUE THREAD

**Issue by leebaird** [darkoperator/dnsrecon#111]
Kali Linux rolling fulling patched.

Example: dnsrecon -d target.com -t std

Exception in thread Thread-9 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "./dnsrecon.py", line 105, in run
  File "/usr/lib/python2.7/Queue.py", line 168, in get
  File "/usr/lib/python2.7/threading.py", line 334, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

**Comment by L1ghtn1ng** [comment]
Closing this as we are now using py3 only
