### ISSUE TITLE
Saving output as JSON

### ISSUE THREAD

**Issue by Frapava** [darkoperator/dnsrecon#130]
**Bug**
[*] Saving records to JSON file: output.json
Traceback (most recent call last):
  File "dnsrecon.py", line 1693, in <module>
    main()
  File "dnsrecon.py", line 1677, in main
    write_json(json_file, returned_records, scan_info)
  File "dnsrecon.py", line 731, in write_json
    json_data = json.dumps(data, sort_keys=True, indent=4, separators=(',', ': '))
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable

**Error while saving output as json**

**To Reproduce**
Steps to reproduce the behaviour:
1. Run tool like this: 'dnsrecon -d domain  -y -k -b -j output.json'
2. See error

**System Information (System that tool is running on):**
 - OS: Kali

**Additional context**
It correctly saves the output as csv and xml.

**Comment by L1ghtn1ng** [comment]
Are you running from git or the Kali package?
________________________________

**Comment by Frapava** [comment]
Oh sorry, git!

**Comment by L1ghtn1ng** [comment]
if you do this on the end it works --disable_check_bindversion for me
