### ISSUE TITLE
[Bug] Error dns.name.EmptyLabel

### ISSUE THREAD

**Issue by Frapava** [darkoperator/dnsrecon#177]
Bug

After having run a bruteforce scan, the program raised the following Error:

Traceback (most recent call last):
  File "dnsrecon.py", line 1716, in <module>
    main()
  File "dnsrecon.py", line 1555, in main
    brt_enum_records = brute_domain(res, dictionary, domain, wildcard_filter, verbose,
  File "dnsrecon.py", line 446, in brute_domain
    brtdata = [future.result() for future in futures.as_completed(future_results)]
  File "dnsrecon.py", line 446, in <listcomp>
    brtdata = [future.result() for future in futures.as_completed(future_results)]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "dnsrecon/lib/dnshelper.py", line 163, in get_ip
    found_ip_add.extend(self.get_a(hostname))
  File "dnsrecon/lib/dnshelper.py", line 118, in get_a
    answers = self.get_answers('A', host_trg)
  File "dnsrecon/lib/dnshelper.py", line 82, in get_answers
    return self._res.resolve(addr_, type_, tcp=self._is_tcp)
  File "/home/fra/.local/lib/python3.8/site-packages/dns/resolver.py", line 1159, in resolve
    resolution = _Resolution(self, qname, rdtype, rdclass, tcp,
  File "/home/fra/.local/lib/python3.8/site-packages/dns/resolver.py", line 523, in __init
    qname = dns.name.from_text(qname, None)
  File "/home/fra/.local/lib/python3.8/site-packages/dns/name.py", line 942, in from_text
    raise EmptyLabel
dns.name.EmptyLabel: A DNS label is empty.

**System Information (System that tool is running on):**
 - OS: Ubuntu 20.04.2 LTS
 - Git Version of dnsrecon

**Comment by L1ghtn1ng** [comment]
This should be fixed now in master
