### ISSUE TITLE
[Bug|] cant run on some targets

### ISSUE THREAD

**Issue by A0x01** [darkoperator/dnsrecon#184]
HI
PLEASE CAN YOU HELP 
Traceback (most recent call last):
  File "/root/Tools/dnsrecon/dnsrecon.py", line 1763, in <module>
    main()
  File "/root/Tools/dnsrecon/dnsrecon.py", line 1650, in main
    std_enum_records = general_enum(res, domain, xfr, bing, yandex,
  File "/root/Tools/dnsrecon/dnsrecon.py", line 925, in general_enum
    check_wildcard(res, domain)
  File "/root/Tools/dnsrecon/dnsrecon.py", line 189, in check_wildcard
    ips = res.get_a(testname)
  File "/root/Tools/dnsrecon/lib/dnshelper.py", line 118, in get_a
    answers = self.get_answers('A', host_trg)
  File "/root/Tools/dnsrecon/lib/dnshelper.py", line 82, in get_answers
    return self._res.resolve(addr_, type_, tcp=self._is_tcp)
AttributeError: 'Resolver' object has no attribute 'resolve'
THANKS

**Comment by L1ghtn1ng** [comment]
What OS you on, python version, DNSrecon version, dnspython version and how you running DNSrecon?
________________________________
From: Martatha Kamil ***@***.***>
Sent: Wednesday, April 14, 2021 6:58:58 PM
To: darkoperator/dnsrecon ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [darkoperator/dnsrecon] [Bug|] cant run on some targets (#184)


Traceback (most recent call last):
File "/root/Tools/dnsrecon/dnsrecon.py", line 1763, in
main()
File "/root/Tools/dnsrecon/dnsrecon.py", line 1650, in main
std_enum_records = general_enum(res, domain, xfr, bing, yandex,
File "/root/Tools/dnsrecon/dnsrecon.py", line 925, in general_enum
check_wildcard(res, domain)
File "/root/Tools/dnsrecon/dnsrecon.py", line 189, in check_wildcard
ips = res.get_a(testname)
File "/root/Tools/dnsrecon/lib/dnshelper.py", line 118, in get_a
answers = self.get_answers('A', host_trg)
File "/root/Tools/dnsrecon/lib/dnshelper.py", line 82, in get_answers
return self.res.resolve(addr, type_, tcp=self._is_tcp)
AttributeError: 'Resolver' object has no attribute 'resolve'

**Comment by L1ghtn1ng** [comment]
Timeout, if there is still an issue with changes that are in master please re-open
