### ISSUE TITLE
[Bug|Feature Request|Other] Resolver' object has no attribute 'resolve'

### ISSUE THREAD

**Issue by abdulx01** [darkoperator/dnsrecon#230]
**I have this issue**

```bash
[*] std: Performing General Enumeration against: example.com.au...
Traceback (most recent call last):
  File "/usr/share/dnsrecon/dnsrecon.py", line 7, in <module>
    __main__.main()
  File "/usr/share/dnsrecon/dnsrecon/cli.py", line 1682, in main
    std_enum_records = general_enum(res, domain, xfr, bing, yandex,
  File "/usr/share/dnsrecon/dnsrecon/cli.py", line 934, in general_enum
    check_wildcard(res, domain)
  File "/usr/share/dnsrecon/dnsrecon/cli.py", line 192, in check_wildcard
    ips = res.get_a(testname)
  File "/usr/share/dnsrecon/dnsrecon/lib/dnshelper.py", line 120, in get_a
    answers = self.get_answers('A', host_trg)
  File "/usr/share/dnsrecon/dnsrecon/lib/dnshelper.py", line 84, in get_answers
    return self._res.resolve(addr_, type_, tcp=self._is_tcp)
AttributeError: 'Resolver' object has no attribute 'resolve'
```

**Comment by L1ghtn1ng** [comment]
What version of DNSrecon are you using plus OS?
On 9 Sep 2022, at 21:09, AbdulRahman ***@***.***> wrote:

﻿

I have this issue

[*] std: Performing General Enumeration against: example.com.au...
Traceback (most recent call last):
  File "/usr/share/dnsrecon/dnsrecon.py", line 7, in <module>
    __main__.main()
  File "/usr/share/dnsrecon/dnsrecon/cli.py", line 1682, in main
    std_enum_records = general_enum(res, domain, xfr, bing, yandex,
  File "/usr/share/dnsrecon/dnsrecon/cli.py", line 934, in general_enum
    check_wildcard(res, domain)
  File "/usr/share/dnsrecon/dnsrecon/cli.py", line 192, in check_wildcard
    ips = res.get_a(testname)
  File "/usr/share/dnsrecon/dnsrecon/lib/dnshelper.py", line 120, in get_a
    answers = self.get_answers('A', host_trg)
  File "/usr/share/dnsrecon/dnsrecon/lib/dnshelper.py", line 84, in get_answers
    return self._res.resolve(addr_, type_, tcp=self._is_tcp)
AttributeError: 'Resolver' object has no attribute 'resolve'

**Comment by abdulx01** [comment]
**It's  1.1.2**

**Comment by abdulx01** [comment]
Linux kali 5.16.0-kali7-amd64

**Comment by CHFR91** [comment]
I have the same problem with DNSRecon v 1.1.3 and Linux 6.1.0-kali5-amd64
