### ISSUE TITLE
Incorrect query causes failure - TXT record - write_db

### ISSUE THREAD

**Issue by FrankSpierings** [darkoperator/dnsrecon#28]
Writing TXT records to a sqlite database will cause the following failure:

Traceback (most recent call last):
  File "dnsrecon.py", line 1666, in <module>
    main()
  File "dnsrecon.py", line 1638, in main
    write_db(results_db, returned_records)
  File "dnsrecon.py", line 796, in write_db
    'values( "%(type)s", "%(name)s" ,"%(strings)s" )' % n
KeyError: 'name'

The TXT record don't have a 'name' key, I'm not sure if that should be correct. 
A fix could be (line 795-796):
query = 'insert into data( type, text) ' + \
             'values( "%(type)s", "%(strings)s" )' % n

**Comment by FrankSpierings** [comment]
This issue seems fixed
