### ISSUE TITLE
All of a sudden!

### ISSUE THREAD

**Issue by AnonymousRonin** [darkoperator/dnsrecon#283]
This suddenly started.  I have no clue what could be the root cause.

 File "/usr/lib/python3/dist-packages/dns/query.py", line 856, in _net_read
    n = sock.recv(count)
        ^^^^^^^^^^^^^^^^
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dnsrecon", line 7, in <module>
    __main__.main()
  File "/usr/share/dnsrecon/dnsrecon/cli.py", line 1888, in main
    std_enum_records = general_enum(
                       ^^^^^^^^^^^^^
  File "/usr/share/dnsrecon/dnsrecon/cli.py", line 1025, in general_enum
    zonerecs = res.zone_transfer()
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/share/dnsrecon/dnsrecon/lib/dnshelper.py", line 466, in zone_transfer
    zone = self.from_wire(dns.query.xfr(ns_srv, self._domain))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/dnsrecon/dnsrecon/lib/dnshelper.py", line 390, in from_wire
    for r in xfr:
  File "/usr/lib/python3/dist-packages/dns/query.py", line 1381, in xfr
    ldata = _net_read(s, 2, mexpiration)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dns/query.py", line 862, in _net_read
    _wait_for_readable(sock, expiration)
  File "/usr/lib/python3/dist-packages/dns/query.py", line 259, in _wait_for_readable
    _wait_for(s, True, False, True, expiration)
  File "/usr/lib/python3/dist-packages/dns/query.py", line 234, in _wait_for
    if not sel.select(timeout):
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by L1ghtn1ng** [comment]
Can you give me reproducible instructions and will see what I can find

On 29 May 2024, at 20:14, AnonymousRonin ***@***.***> wrote:

﻿

This suddenly started. I have no clue what could be the root cause.

File "/usr/lib/python3/dist-packages/dns/query.py", line 856, in _net_read
n = sock.recv(count)
^^^^^^^^^^^^^^^^
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/dnsrecon", line 7, in
main.main()
File "/usr/share/dnsrecon/dnsrecon/cli.py", line 1888, in main
std_enum_records = general_enum(
^^^^^^^^^^^^^
File "/usr/share/dnsrecon/dnsrecon/cli.py", line 1025, in general_enum
zonerecs = res.zone_transfer()
^^^^^^^^^^^^^^^^^^^
File "/usr/share/dnsrecon/dnsrecon/lib/dnshelper.py", line 466, in zone_transfer
zone = self.from_wire(dns.query.xfr(ns_srv, self._domain))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/dnsrecon/dnsrecon/lib/dnshelper.py", line 390, in from_wire
for r in xfr:
File "/usr/lib/python3/dist-packages/dns/query.py", line 1381, in xfr
ldata = _net_read(s, 2, mexpiration)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/dns/query.py", line 862, in _net_read
_wait_for_readable(sock, expiration)
File "/usr/lib/python3/dist-packages/dns/query.py", line 259, in _wait_for_readable
_wait_for(s, True, False, True, expiration)
File "/usr/lib/python3/dist-packages/dns/query.py", line 234, in _wait_for
if not sel.select(timeout):
^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/selectors.py", line 415, in select
fd_event_list = self._selector.poll(timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by AnonymousRonin** [comment]
From my home dir.; dnsrecon -a -d atf.gov

I'm trying to think of any changes in or new installs but there's nothing I can find. Tried doing update and upgrade but no success.

I haven't done install --reinstall because although it may work, it doesn't tell me what the issue is/was.

Thanks for your time.

Sent from Proton Mail Android

-------- Original Message --------
