### ISSUE TITLE
Issue with DNS SEC enabled domain

### ISSUE THREAD

**Issue by pavel-odintsov** [darkoperator/dnsrecon#59]
Hello!

I'm trying to check my own domain lineratedev.net and do not have any success:

```
./dnsrecon.py -d lineratedev.net
[*] Performing General Enumeration of Domain: lineratedev.net
[*] DNSSEC is configured for lineratedev.net
Traceback (most recent call last):
  File "./dnsrecon.py", line 1682, in <module>
    main()
  File "./dnsrecon.py", line 1640, in main
    spf_enum, do_whois, zonewalk)
  File "./dnsrecon.py", line 957, in general_enum
    dns_sec_check(domain, res)
  File "./dnsrecon.py", line 862, in dns_sec_check
    nsectype = get_nsec_type(domain, res)
  File "./dnsrecon.py", line 847, in get_nsec_type
    answer = get_a_answer(target, res._res.nameservers[0], res._res.timeout)
  File "./dnsrecon.py", line 1204, in get_a_answer
    answer = dns.query.udp(query, ns, timeout)
  File "/usr/local/lib/python2.7/dist-packages/dns/query.py", line 254, in udp
    one_rr_per_rrset=one_rr_per_rrset)
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 808, in from_wire
    reader.read()
  File "/usr/local/lib/python2.7/dist-packages/dns/message.py", line 751, in read
    raise TrailingJunk
dns.message.TrailingJunk: The DNS packet passed to from_wire() has extra junk at the end of it.
```

Do you have some ideas how I could resolve this issue?

Thank you!

**Comment by darkoperator** [comment]
Weird, what OS and versions of the libraries are you using?

On OS X with latest versions of dnspython

infidel01-2:dnsrecon carlos$ ./dnsrecon.py -d lineratedev.net
[*] Performing General Enumeration of Domain: lineratedev.net
[*] DNSSEC is configured for lineratedev.net
[*] DNSKEYs:
[*]    	NSEC KSk ECDSAP256SHA256 99db2cc14cabdc33d6d77da63a2f15f7 1112584f234e8d1dc428e39e8a4a97e1 aa271a555dc90701e17e2a4c4b6f120b 7c32d44f4ac02bd894cf2d4be7778a19
[*]    	NSEC ZSK ECDSAP256SHA256 9283dbc3dc26619ee081c8e743a6b21f 284768334c6042ca4ea4fea911ab6695 9271caff94172b9b5d19d4fb901c1dc0 ce18a2fac6f43d81641f5aeec4b85ee6
[*]    	 SOA art.ns.cloudflare.com 173.245.59.102
[*]    	 NS dina.ns.cloudflare.com 173.245.58.107
[*]    	 NS dina.ns.cloudflare.com 2400:cb00:2049:1::adf5:3a6b
[*]    	 NS art.ns.cloudflare.com 173.245.59.102
[*]    	 NS art.ns.cloudflare.com 2400:cb00:2049:1::adf5:3b66
[-] Could not Resolve MX Records for lineratedev.net
[*]    	 A lineratedev.net 104.18.44.193
[*]    	 A lineratedev.net 104.18.45.193
[*]    	 AAAA lineratedev.net 2400:cb00:2048:1::6812:2cc1
[*]    	 AAAA lineratedev.net 2400:cb00:2048:1::6812:2dc1
[*] Enumerating SRV Records
[-] No SRV Records Found for lineratedev.net
[*] 0 Records Found

**Comment by SyntheticOxygen** [comment]
I have the same problem on Kali Linux Rolling Releases

nsrecon -d vs-breider.nl
[*] Performing General Enumeration of Domain: vs-breider.nl
[*] DNSSEC is configured for vs-breider.nl
Traceback (most recent call last):
  File "./dnsrecon.py", line 1676, in <module>
    main()
  File "./dnsrecon.py", line 1634, in main
    spf_enum, do_whois, zonewalk)
  File "./dnsrecon.py", line 951, in general_enum
    dns_sec_check(domain, res)
  File "./dnsrecon.py", line 856, in dns_sec_check
    nsectype = get_nsec_type(domain, res)
  File "./dnsrecon.py", line 841, in get_nsec_type
    answer = get_a_answer(target, res._res.nameservers[0], res._res.timeout)
  File "./dnsrecon.py", line 1198, in get_a_answer
    answer = dns.query.udp(query, ns, timeout)
  File "/usr/lib/python2.7/dist-packages/dns/query.py", line 254, in udp
    one_rr_per_rrset=one_rr_per_rrset)
  File "/usr/lib/python2.7/dist-packages/dns/message.py", line 808, in from_wire
    reader.read()
  File "/usr/lib/python2.7/dist-packages/dns/message.py", line 751, in read
    raise TrailingJunk
dns.message.TrailingJunk: The DNS packet passed to from_wire() has extra junk at the end of it.
