### ISSUE TITLE
Bad return type when getting SOA record

### ISSUE THREAD

**Issue by j0k2r** [darkoperator/dnsrecon#87]
Hi,

For some domains an exception is raised when dnsrecon try to get SOA record:
```
[*] Performing General Enumeration of Domain: *******
[*] Checking for Zone Transfer for ******* name servers
[*] Resolving SOA Record
[-] Could not obtain the domains SOA Record.
[-] DNSSEC is not configured for *******
Traceback (most recent call last):
  File "/opt/dnsrecon/dnsrecon.py", line 1707, in <module>
    main()
  File "/opt/dnsrecon/dnsrecon.py", line 1665, in main
    std_enum_records = general_enum(res, domain, xfr, goo, bing, spf_enum, do_whois, do_crt, zonewalk)
  File "/opt/dnsrecon/dnsrecon.py", line 951, in general_enum
    found_soa_records = res.get_soa()
  File "/opt/dnsrecon/lib/dnshelper.py", line 217, in get_soa
    name = rdata[0].mname.to_text()
AttributeError: 'CNAME' object has no attribute 'mname'
```

 After some investigations, it seems that `rdata[0]` is a `dns.rdtypes.ANY.CNAME.CNAME` type and don't have `mname` attribute.

I added a simple workaround, to resolve the problem:
 ```
--- a/lib/dnshelper.py
+++ b/lib/dnshelper.py
@@ -214,6 +214,8 @@ class DnsHelper:
                 answers = response.authority
             for rdata in answers:
                 # A zone only has one SOA record so we select the first.
+                if not isinstance(rdata[0], dns.rdtypes.ANY.SOA.SOA):
+                    return []
                 name = rdata[0].mname.to_text()
                 ipv4_answers = self._res.query(name, 'A', tcp=tcp)
                 for ardata in ipv4_answers:
```

Can you confirm the solution validity ?

**Comment by TAbdiukov** [comment]
can confirm @j0k2r 's fix works as the script fails in some specific cases. Try it on sso.ns.agency

**Comment by tsellers-r7** [comment]
@darkoperator - This can be closed now.
